### PR TITLE
Create bower.json

### PR DESCRIPTION
**Pull request by cornernote**
added so minetest-bower gets a screenshot
https://minetest-bower.herokuapp.com/mods/volcano

### CODE REVIEW

**Comment by cornernote** [comment]
You may also consider using a README.md file for prettier formatting.

There is a template readme file here:
https://minetest-bower.herokuapp.com/mods/readme/volcano

**Comment by paramat** [comment]
Bower looks cool but i don't want to add a file just for a mod repo, you can add a screenshot to bower manually if you want.

**Comment by cornernote** [comment]
Could you add a screenshot.png to the repo instead?

**Comment by paramat** [comment]
Perhaps, what's the minimum size required?

**Comment by HybridDog** [comment]
> Could you add a screenshot.png to the repo instead?

downloading the mod would take a lot more time l guess

**Comment by cornernote** [comment]
There are no minimum/maximum size requirements for the image.  If repo space is the issue then the bower.json file is better as it takes up less space and provides more information about the mod.

Not sure why there is resistance to adding information about the project to the project's repository.

I don't have a way to add screenshots other than these methods to the bower repo.  If nobody wants to help by providing info about their packages then perhaps I'll look at harvesting the information from the forums at some stage in the future.  I made it so that it syncs the information from the repo so that there is minimal effort required to keep it updated.  I just thought that people would like to have a mod repository that offered a bit more structure than the forums.

**Comment by paramat** [comment]
I'm very busy but want to do these things myself. I do indeed need to add images and info to the readme, as with many of my mods. After 0.4.13 release i'll be returning to modding and have more time.

**Pull request closed without merging**
